# Generated by Django 3.1.4 on 2021-01-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crackels_mod',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('patient_id', models.IntegerField()),
                ('firstname1', models.CharField(max_length=255)),
                ('lastname1', models.CharField(max_length=255)),
                ('AudioFile', models.FileField(default='', upload_to='home/sounds_file')),
                ('PFT_Location', models.CharField(choices=[('location1', 'Location1'), ('location2', 'Location2'), ('location3', 'Location3'), ('location4', 'Location4'), ('location5', 'Location5'), ('location6', 'Location6')], default='location1', max_length=20)),
                ('PFT_image', models.FileField(blank=True, upload_to='images/')),
                ('Comment_box', models.TextField()),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
